import type { Vinyl } from "@/types/vinyl"

export const SEED_VINYLS: Vinyl[] = [
	{
		id: "vnl_01kindofblue",
		title: "Kind of Blue",
		artist: "Miles Davis",
		year: 1959,
		genre: "Jazz",
		condition: "Near Mint",
		isColoredVinyl: false,
		pricePaid: 42.5,
		catalogNumber: "CL 1355",
		notes: "Columbia six-eye pressing. Quiet vinyl.",
		acquiredAt: "2022-03-14",
	},
	{
		id: "vnl_02abbeyroad",
		title: "Abbey Road",
		artist: "The Beatles",
		year: 1969,
		genre: "Rock",
		condition: "Very Good",
		isColoredVinyl: false,
		pricePaid: 28,
		catalogNumber: "SO-383",
		notes: "US Apple pressing. Light sleeve wear.",
		acquiredAt: "2021-11-02",
	},
	{
		id: "vnl_03randomaccess",
		title: "Random Access Memories",
		artist: "Daft Punk",
		year: 2013,
		genre: "Electronic",
		condition: "Mint",
		isColoredVinyl: true,
		pricePaid: 55,
		catalogNumber: "88883716861",
		notes: "Clear vinyl anniversary reissue.",
		acquiredAt: "2023-06-21",
	},
	{
		id: "vnl_04goldberg",
		title: "Goldberg Variations",
		artist: "Glenn Gould",
		year: 1956,
		genre: "Classical",
		condition: "Good",
		isColoredVinyl: false,
		pricePaid: 18.75,
		catalogNumber: "ML 5060",
		notes: "1955 recording. Surface noise on side B.",
		acquiredAt: "2020-09-08",
	},
	{
		id: "vnl_05illmatic",
		title: "Illmatic",
		artist: "Nas",
		year: 1994,
		genre: "Hip-Hop",
		condition: "Near Mint",
		isColoredVinyl: false,
		pricePaid: 35,
		catalogNumber: "C 57684",
		notes: "Columbia original. Clean labels.",
		acquiredAt: "2024-01-19",
	},
	{
		id: "vnl_06blue",
		title: "Blue",
		artist: "Joni Mitchell",
		year: 1971,
		genre: "Folk",
		condition: "Very Good",
		isColoredVinyl: false,
		pricePaid: 32,
		catalogNumber: "MS 2038",
		notes: "Reprise gatefold. Slight ring wear.",
		acquiredAt: "2022-08-30",
	},
	{
		id: "vnl_07whatsgoingon",
		title: "What's Going On",
		artist: "Marvin Gaye",
		year: 1971,
		genre: "Soul",
		condition: "Fair",
		isColoredVinyl: false,
		pricePaid: 12,
		catalogNumber: "TS-310",
		notes: "Well-loved copy. Still plays through.",
		acquiredAt: "2019-05-12",
	},
	{
		id: "vnl_08nevermind",
		title: "Nevermind",
		artist: "Nirvana",
		year: 1991,
		genre: "Punk",
		condition: "Mint",
		isColoredVinyl: true,
		pricePaid: 48,
		catalogNumber: "DGCS-24425",
		notes: "Blue swirl vinyl reissue, sealed then opened once.",
		acquiredAt: "2025-02-04",
	},
]
